import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';


export interface GameState {
  status: 'home' | 'new' | 'started';
  type: 'classic' | 'ranked';
  mode: 'unranked' | 'ranked';
}

const initialState: GameState = {
  status: 'home',
  type: 'ranked',
  mode: 'unranked',
};


export const gameSlice = createSlice({
  name: 'game',
  initialState,
  reducers: {
    startGame: (state) => {
      state.status = 'started';
    },
    startNewGame: (state) => {
      state.status = 'new';
    },
    goHome: (state) => {
      state.status = 'home';
    },
    setGameType: (state, action: PayloadAction<'classic' | 'ranked'>) => {
      state.type = action.payload;
    },
    setGameMode: (state, action: PayloadAction<'unranked' | 'ranked'>) => {
      state.mode = action.payload;
      if (action.payload === 'ranked') {
        state.type = 'ranked';
      }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {
  //   builder
  //     .addCase(incrementAsync.pending, (state) => {
  //       state.status = 'loading';
  //     })
  //     .addCase(incrementAsync.fulfilled, (state, action) => {
  //       state.status = 'idle';
  //       state.value += action.payload;
  //     })
  //     .addCase(incrementAsync.rejected, (state) => {
  //       state.status = 'failed';
  //     });
  // },
});

export const { startGame, startNewGame, goHome, setGameType, setGameMode } =
  gameSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`

export const selectGameStatus = (state: RootState) => state.game.status;
export const selectGameType = (state: RootState) => state.game.type;
export const selectGameMode = (state: RootState) => state.game.mode;


// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectPlayerCount(getState());
//     if (currentValue % 2 === 1) {
//       dispatch(incrementByAmount(amount));
//     }
//   };

export default gameSlice.reducer;
